stages:
  - prepare
  - build
  - dockerize
  - deploy

generate-jooq:
  stage: prepare
  image: maven:3.9-eclipse-temurin-21
  services:
    - name: postgres:15
      alias: postgres
  variables:
    POSTGRES_DB: jooq_db
    POSTGRES_USER: jooq_user
    POSTGRES_PASSWORD: jooq_password
    DB_HOST: postgres
    DB_PORT: 5432
    DB_NAME: jooq_db
    DB_USER: jooq_user
    DB_PASSWORD: jooq_password
  before_script:
    - apt-get update && apt-get install -y postgresql-client
    - until pg_isready -h $DB_HOST -p $DB_PORT; do sleep 1; done
  script:
    - mvn clean liquibase:update jooq-codegen:generate
  artifacts:
    paths:
      - target/generated-sources/jooq

build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  dependencies:
    - generate-jooq
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar

dockerize:
  stage: dockerize
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  dependencies:
    - build
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  script:
    - echo "Deploying to VPS or elsewhere..."
